apiVersion: v1
kind: Config
clusters:
- name: "quickstart-aws-custom"
  cluster:
    server: "https://rancher.52.78.117.163.sslip.io/k8s/clusters/c-m-mwmmj5wm"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0TmpZNQpNRE0zTURBZUZ3MHlNekEyTVRNeU1UQTJNVEJhRncwek16QTJNVEF5TVRBMk1UQmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZzJOamt3TXpjd01Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRVdySkI3WDRFN0F6WApmd29IRHZOQXJuZzBCbjNYeGJKVkZmSUdQN\
      DNUeVAvTTI5NWIwMDliWkszTTlLdW9KUWM5bk9sRnJsTTFqa1ZpCkphOGpFckZUVUtOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      W1PNVdRWGFsclVnUy9LTW54YmpNaXozWEhJTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDOQpPb\
      kFLeFVCZ0kxbWdoYmRSYjdrZUNGN09GTnJndldnbXQzSGJCdEdjN0FJZ09tam4xSjdqT3I4cmRyd\
      XIxV1hRCjZqakpoak9uNTZKN3lHK0d4Z1ppT1hRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "quickstart-aws-custom"
  user:
    token: "kubeconfig-user-wzv7m4995x:t7rjv7vcvf4xhnwfw6mw487chvqrbhzdpd76v9fl2xm9r58m652mmh"


contexts:
- name: "quickstart-aws-custom"
  context:
    user: "quickstart-aws-custom"
    cluster: "quickstart-aws-custom"

current-context: "quickstart-aws-custom"
